using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MasterFudgeMk2.Devices
{
    public partial class Z80A
    {
        static DDFDCBOpcodeDelegate[] opcodesPrefixDDFDCB = new DDFDCBOpcodeDelegate[]
        {
			/* 0x00 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.RotateLeftCircular(address); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.RotateRightCircular(address); }),
            UnimplementedOpcodeDDFDCB,
			/* 0x10 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.RotateLeft(address); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.RotateRight(address); }),
            UnimplementedOpcodeDDFDCB,
			/* 0x20 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ShiftLeftArithmetic(address); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ShiftRightArithmetic(address); }),
            UnimplementedOpcodeDDFDCB,
			/* 0x30 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ShiftLeftLogical(address); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ShiftRightLogical(address); }),
            UnimplementedOpcodeDDFDCB,
			/* 0x40 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.TestBit(c.ReadMemory8(address), 0); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.TestBit(c.ReadMemory8(address), 1); }),
            UnimplementedOpcodeDDFDCB,
			/* 0x50 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.TestBit(c.ReadMemory8(address), 2); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.TestBit(c.ReadMemory8(address), 3); }),
            UnimplementedOpcodeDDFDCB,
			/* 0x60 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.TestBit(c.ReadMemory8(address), 4); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.TestBit(c.ReadMemory8(address), 5); }),
            UnimplementedOpcodeDDFDCB,
			/* 0x70 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.TestBit(c.ReadMemory8(address), 6); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.TestBit(c.ReadMemory8(address), 7); }),
            UnimplementedOpcodeDDFDCB,
			/* 0x80 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ResetBit(address, 0); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ResetBit(address, 1); }),
            UnimplementedOpcodeDDFDCB,
			/* 0x90 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ResetBit(address, 2); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ResetBit(address, 3); }),
            UnimplementedOpcodeDDFDCB,
			/* 0xA0 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ResetBit(address, 4); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ResetBit(address, 5); }),
            UnimplementedOpcodeDDFDCB,
			/* 0xB0 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ResetBit(address, 6); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.ResetBit(address, 7); }),
            UnimplementedOpcodeDDFDCB,
			/* 0xC0 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.SetBit(address, 0); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.SetBit(address, 1); }),
            UnimplementedOpcodeDDFDCB,
			/* 0xD0 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.SetBit(address, 2); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.SetBit(address, 3); }),
            UnimplementedOpcodeDDFDCB,
			/* 0xE0 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.SetBit(address, 4); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.SetBit(address, 5); }),
            UnimplementedOpcodeDDFDCB,
			/* 0xF0 */
			UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.SetBit(address, 6); }),
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            UnimplementedOpcodeDDFDCB,
            new DDFDCBOpcodeDelegate((Z80A c, ref Register r, ushort address) => { c.SetBit(address, 7); }),
            UnimplementedOpcodeDDFDCB,
        };
    }
}
