using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MasterFudgeMk2.Devices
{
    public partial class Z80A
    {
        static DDFDOpcodeDelegate[] opcodesPrefixDDFD = new DDFDOpcodeDelegate[]
        {
			/* 0x00 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add16(ref r, c.bc.Word, false); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
			/* 0x10 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add16(ref r, c.de.Word, false); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
			/* 0x20 */
			UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadRegisterImmediate16(ref r.Word); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadMemory16(c.ReadMemory16(c.pc), r.Word); c.pc += 2; }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Increment16(ref r.Word); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.Increment8(ref r.High); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.Decrement8(ref r.High); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ r.High = c.ReadMemory8(c.pc++); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add16(ref r, r.Word, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadRegister16(ref r.Word, c.ReadMemory16(c.ReadMemory16(c.pc))); c.pc += 2; }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Decrement16(ref r.Word); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.Increment8(ref r.Low); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.Decrement8(ref r.Low); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ r.Low = c.ReadMemory8(c.pc++); }),
            UnimplementedOpcodeDDFD,
			/* 0x30 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.IncrementMemory8(c.CalculateIXIYAddress(r)); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.DecrementMemory8(c.CalculateIXIYAddress(r)); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadMemory8(c.CalculateIXIYAddress(r), c.ReadMemory8(c.pc++)); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add16(ref r, c.sp, false); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
			/* 0x40 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.bc.High, r.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.bc.High, r.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.bc.High = c.ReadMemory8(c.CalculateIXIYAddress(r)); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.bc.Low, r.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.bc.Low, r.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.bc.Low = c.ReadMemory8(c.CalculateIXIYAddress(r)); }),
            UnimplementedOpcodeDDFD,
			/* 0x50 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.de.High, r.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.de.High, r.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.de.High = c.ReadMemory8(c.CalculateIXIYAddress(r)); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.de.Low, r.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.de.Low, r.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.de.Low = c.ReadMemory8(c.CalculateIXIYAddress(r)); }),
            UnimplementedOpcodeDDFD,
			/* 0x60 */
			new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.High, c.bc.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.High, c.bc.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.High, c.de.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.High, c.de.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.High, r.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.High, r.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.hl.High = c.ReadMemory8(c.CalculateIXIYAddress(r)); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.High, c.af.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.Low, c.bc.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.Low, c.bc.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.Low, c.de.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.Low, c.de.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.Low, r.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.Low, r.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.hl.Low = c.ReadMemory8(c.CalculateIXIYAddress(r)); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref r.Low, c.af.High, false); }),
			/* 0x70 */
			new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadMemory8(c.CalculateIXIYAddress(r), c.bc.High); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadMemory8(c.CalculateIXIYAddress(r), c.bc.Low); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadMemory8(c.CalculateIXIYAddress(r), c.de.High); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadMemory8(c.CalculateIXIYAddress(r), c.de.Low); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadMemory8(c.CalculateIXIYAddress(r), c.hl.High); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadMemory8(c.CalculateIXIYAddress(r), c.hl.Low); }),
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.LoadMemory8(c.CalculateIXIYAddress(r), c.af.High); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.af.High, r.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { /* XXX */ c.LoadRegister8(ref c.af.High, r.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.af.High = c.ReadMemory8(c.CalculateIXIYAddress(r)); }),
            UnimplementedOpcodeDDFD,
			/* 0x80 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add8(r.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add8(r.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add8(c.ReadMemory8(c.CalculateIXIYAddress(r)), false); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add8(r.High, true); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add8(r.Low, true); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Add8(c.ReadMemory8(c.CalculateIXIYAddress(r)), true); }),
            UnimplementedOpcodeDDFD,
			/* 0x90 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Subtract8(r.High, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Subtract8(r.Low, false); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Subtract8(c.ReadMemory8(c.CalculateIXIYAddress(r)), false); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Subtract8(r.High, true); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Subtract8(r.Low, true); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Subtract8(c.ReadMemory8(c.CalculateIXIYAddress(r)), true); }),
            UnimplementedOpcodeDDFD,
			/* 0xA0 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.And8(r.High); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.And8(r.Low); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.And8(c.ReadMemory8(c.CalculateIXIYAddress(r))); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Xor8(r.High); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Xor8(r.Low); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Xor8(c.ReadMemory8(c.CalculateIXIYAddress(r))); }),
            UnimplementedOpcodeDDFD,
			/* 0xB0 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Or8(r.High); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Or8(r.Low); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Or8(c.ReadMemory8(c.CalculateIXIYAddress(r))); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Cp8(r.High); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Cp8(r.Low); }),
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Cp8(c.ReadMemory8(c.CalculateIXIYAddress(r))); }),
            UnimplementedOpcodeDDFD,
			/* 0xC0 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.ExecuteOpDDFDCB(c.ReadMemory8((ushort)(c.pc + 1)), ref r); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
			/* 0xD0 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
			/* 0xE0 */
			UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Pop(ref r); }),
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.ExchangeStackRegister16(ref r); }),
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.Push(r); }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.pc = r.Word; }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
			/* 0xF0 */
			UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            new DDFDOpcodeDelegate((Z80A c, ref Register r) => { c.sp = r.Word; }),
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
            UnimplementedOpcodeDDFD,
        };
    }
}
